### ISSUE TITLE
Experiments in DECK/CMIP6 mips vs CMIP

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#25]
At version 1.00.02 of the data request the assignment of the core experiments to MIPs appears to be inconsistent with es-doc and [Eyring et al.](http://www.geosci-model-dev.net/9/1937/2016/gmd-9-1937-2016.html). 

According to es-doc.org the historical experiments belong to CMIP6 and the 1pctCO2, abrupt-4xCO2, amip, piControl and esm-piControl belong to the DECK. In the data request the [DECK](http://clipc-services.ceda.ac.uk/dreq/u/DECK.html) and [CMIP6](http://clipc-services.ceda.ac.uk/dreq/u/CMIP6.html) MIPs have no associated experiments, with all of the above in the "[CMIP](http://clipc-services.ceda.ac.uk/dreq/u/CMIP.html)" MIP.

While it is not impossible to work around this issue it does add complexity to working between these two sources.

**Comment by taylor13** [comment]
The  GMD paper by Eyring et al. refers to a collection of experiments whereas the activity_id identifies the MIP (or MIPs) responsible for each experiment.  I know this is a little confusing, but it was done this way in order to simplify "searching" for data.  Since the CMIP panel is responsible for the DECK *and* historical experiments, those experiments have activity_id="CMIP".    The phase (or "era") of CMIP is recorded elsewhere. 

Perhaps ES-DOC will consider following this same approach to avoid inconsistency and confusion.

**Comment by charliepascoe** [comment]
In ES-Doc we think of experiments as belonging to projects, for the most part there is a direct correspondence between an ES-Doc Project, a MIP and activity-id with the exception of the DECK experiments.  Therefore I think the way forward with the ES-Doc documentation would be to place the DECK experiments and the historical experiments under a new project called CMIP and to record "DECK" as a keyword.

**Comment by taylor13** [comment]
I think your proposed way forward is a good idea.  Thanks.
