### ISSUE TITLE
ISMIP requests from ScenarioMIP/PMIP missing

### ISSUE THREAD

**Issue by rssmith** [cmip6dr/Request#62]
The ISMIP6 experiment description  (Nowicki et al., GMD 9 '16) requires diagnostics not only from the DECK and Historical simulations, but also some ScenarioMIP (ssp585, ssp585-ext) and PMIP4 (lig127k) experiments. 

The summary of the cross-MIP data request at http://clipc-services.ceda.ac.uk/dreq/tab01_3_3.html suggests that something has gone awry in the data request and ISMIP6 has not requested any data from ScenarioMIP or PMIP. Does the ISMIP6 data request need amending?

**Comment by matthew-mizielinski** [comment]
This issue is still present at version 01.00.20 of the data request.

**Comment by martinjuckes** [comment]
Sorry for the delay in getting to this. The original request from ISMIP6 was for lgm127k rather than lig127k .. which caused the error. For ssp585: there is no `ssp585-ext` , but there are options to run `ssp585` for only 100 years or for an extended period of 300 years (the `-ext` suffix is used for extensions of the `historical` run because there is a conceptual change in the way in which forcing is prescribed in the extension period, but this does not apply to `ssp585` ), so I have set the ISMIP6 request to be for 300 years.

**Comment by martinjuckes** [comment]
This is now fixed for 01.00.22

**Comment by matthew-mizielinski** [comment]
I've raised this in a separate forum, but for completeness; ScenarioMIP does call for an `ssp585-ext` experiment, but this has not made it into CVs, ES-Doc or the data request for some reason.
