### ISSUE TITLE
Odd DCCP variables in Eyr ? (DR 1.00.16)

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/Request#68]
I'm wandering and losing myself in the DR, while checking PMIP related _stuff_...

I have come across some variables requested only by DCCP that look _odd_. There is a bunch of variables in **Eyr**, from _treeFrac_ to _residualFrac_:
- that don't have _time_ as their last dimension: e.g. _dimensions_ for treeFrac is **longitude latitude time typetree**
- where the extra dimension is of type **character**, which is not always very convenient to use, and the allowed/expected values are not listed in the DR. e.g, nothing in the _requested_ part of [typetree](http://clipc-services.ceda.ac.uk/dreq/u/dim:typetree.html)

Is this correct??? @durack1 ?

I have had a very quick look at the DCPP paper (@taylor13 is a co-author) but I have not found obvious extra details. I have also asked LSCE vegetation people but they did not know about these variables. The closest thing they new about was [gppLut](http://clipc-services.ceda.ac.uk/dreq/u/d22d8a9e-4a9f-11e6-b84e-ac72891c3257.html) that has a [landUse ](http://clipc-services.ceda.ac.uk/dreq/u/dim:landUse.html) dimension with 4 requested character values (`primary_and_secondary_land  pastures  crops  urban`)

**Comment by martinjuckes** [comment]
In the data request database record defining the variable structure [Temporal mean, Global field (single level) [XY-na] {:typetree}](http://clipc-services.ceda.ac.uk/dreq/u/fa21f210-267c-11e7-9bed-ac72891c3257.htm) it is clear that `typetree` is a `coordinate` rather than a `dimension`, and in the MIP tables follow the CMIP5 convention in having coordinates listed after the time dimension. Every variable with standard name `area_fraction` must, according to the CF convention have a `coordinate` attribute which points to a variable identifying the area type . See the Data Request page on [area coverage](https://www.earthsystemcog.org/projects/wip/area_coverage) for more discussion.

**Comment by taylor13** [comment]
Actually, I think area_fraction has no special requirements (at least I couldn't find any mention of it).  A variable with standard name "area_type", on the other hand, does require a coordinate defining the "type".

In CMIP5 there was no scalar coordinate dimension defined for variables like treeFrac, and I don't think it is essential, since it is obvious from the variable name and long_name. If it is included, then this will expand the list of coordinates that need to be defined (one for each area_type that is singled out  ... order 10, I think)

**Comment by martinjuckes** [comment]
The CF Standard name description for `area_fraction` states `To specify which area is quantified by a variable of "area_fraction", provide a coordinate variable or scalar coordinate variable of "area_type"`, which could be read as an instruction or guidance. Ticket https://cf-trac.llnl.gov/trac/ticket/153 tries to sort out the difference between requirements and suggestions, and currently identifies the use of an area_type as required ... but is hanging in limbo. I have, however, used the current status of this ticket to systematically analyse the compliance of the request with requirements which relate to specific standard names. In the CMIP6 request the majority of `area_fraction` variables do make use of an `area_type` coordinate.

**Comment by taylor13** [comment]
Thanks for pointing to proposal 153.  If what you propose can be implemented in a way that avoids making CMIP5 files non-compliant (with respect to this issue), then I support it.  I can see the value of defining a coordinate dimension to identify "type" using controlled vocabularies.  

Does the current area_type table ( http://cfconventions.org/Data/area-type-table/6/build/area-type-table.html) contain all the options needed for CMIP6?

**Comment by jypeter** [comment]
OK. Thanks for the details!

**Comment by martinjuckes** [comment]
For information on non-conformant variables see here:  https://www.earthsystemcog.org/projects/wip/area_coverage

**Comment by martinjuckes** [comment]
For information on non-conformant variables see here:  https://www.earthsystemcog.org/projects/wip/area_coverage
