### ISSUE TITLE
Inclusion of ScenarioMIP extension experiments

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/Request#73]
In the [ScenarioMIP GMD paper](https://www.geosci-model-dev.net/9/3461/2016/) there are three extension experiments to `ssp585`, `ssp534-over` and `ssp126` (see table 2 in GMD paper). The CVs include options on the end year (2100 or 2300, see [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/d2c7e38fd827ee55aa171203f10f022b8b7480c9/CMIP6_experiment_id.json#L6301) for example, but neither the data request nor ES-Doc include this information.

Is it straightforward, and safe for current users of the data request, to introduce alternative end dates/nyears for these experiments? 

An alternative would be to separate the extensions into distinct experiments (as used in the historical extension `historical-ext`, and in the ScenarioMIP paper), which would allow restricting data volumes more straightforwardly, but would require a change to the CVs to maintain consistency and a coherent change in ES-Doc.

**Comment by taylor13** [comment]
I don't think we should add new experiments at this point.  If only 1 end-date is allowed, then I would specify the later of the two.  A modeling group can, of course, elect to only to part of the experiment (ending at the earlier date).  
The reason that historical-ext was defined was to distinguish the portion of the run where forcing is likely to be less uniform across models (because there are no "standard" forcing datasets for the -ext portion).

**Comment by martinjuckes** [comment]
I believe it is safe for modeling groups to extend these experiments. I'm not sure if prePare checks the date associated with data submitted, but any check would be done on the basis of the CVs,

**Comment by taylor13** [comment]
No, I don't think PrePARE checks this.
