### ISSUE TITLE
Title for longitude is incorrect

### ISSUE THREAD

**Issue by sherimickelson** [cmip6dr/Request#82]
The title for longitude is set being set to 
"Radiation Wavelength 550 nanometers"

(weblink in dreq: http://clipc-services.ceda.ac.uk/dreq/u/dim:longitude.html)

**Comment by matthew-mizielinski** [comment]
@sherimickelson, thanks for reporting this. In the ticket I've referenced above I've noted that if propagated into the MIP tables this would result in the `long_name` attribute on the longitude coordinate (in most files) being incorrect.

@martinjuckes, @taylor13, can this be fixed in dreq 01.00.24 (i.e. re-tag this release) or do we have to wait for the next version?

**Comment by taylor13** [comment]
As you might have noted, we haven't yet generated CMOR tables based on dreq 01.00.24.  We intend to do that possibly as soon as today.  We'll try to substitute "Longitude" for "Radiation Wavelength 550 nanometers", but I'll have to speak to @doutriaux1 .

@martinjuckes , do you think this is a single mistake or indicative of a more extensive problem with long_name?

**Comment by martinjuckes** [comment]
Corrected.
