### ISSUE TITLE
Grid specifications -- DynVar

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/Request#87]
DynVar request links have "model grid" as the "grid" value ... should be changed to `native` -- there may be other errors.

**Comment by edwinpgerber** [comment]
I wanted to follow up on this.  We did not specify the horizontal output grid in the GMD paper outlining the MIP request (http://doi.org/10.5194/gmd-9-3413-2016).  Our intent was to leave this to model center's discretion, so that variables could be written out on the horizontal grids used for other CMIP6 output.  We assumed that this would be the native grid, but for models with non-standard grids (e.g. a cubed sphere), we would ask for data on your standard interpolation to a latitude longitude grid.  

As noted in the paper, we ask for the diagnostics (e.g., Eliassen-Palm fluxes) to be computed on the native grids, or as close to them as possible.

**Comment by martinjuckes** [comment]
Since modeling groups are generally ignoring the grid requests as excessively complex, this is left unchanged.
